[package]
name = "qprov"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dilithium = "0.1.1"
openssl = "0.10.48"
rand = "0.4.6"
rmce = { version = "0.1.0", path = "../rmce" }
